# Your local wallets config. Localhost is the only case when this app will need to use more than 1 currency at a time

bitcoin:
  rpc_username: "btctest"
  rpc_password: "btcword"
  rpc_host: 'sandbox.noveltylab.com'
  rpc_port: 12346
litecoin:
  rpc_username: "nixoid"
  rpc_password: "98g7w98duldksutw987ye87y"
  rpc_host: 'localhost'
  rpc_port: 9332
peercoin:
  rpc_username: "nixoid"
  rpc_password: "pppass89374th9w8eh"
  rpc_host: 'localhost'
  rpc_port: 8932
ripple:
  rpc_username: "rf3hVTFEXbWUmsVxWsD4R37NHDw26nR9o2"
  rpc_password: "shUwk6M8tkfC5jHgEbe6gHdEidjym"
  rpc_host: 'ripple-staging.holytransaction.com'
  rpc_port: 51234
dogecoin:
  rpc_username: "irg87hrg8"
  rpc_password: "8w9g7hw98ee8r9g7h298r7hw98rt7hw9er8ht7wertwe8rghw9r87ghw987whe8r"
  rpc_host: 'localhost'
  rpc_port: 8432
blackcoin:
  rpc_username: "darkcoinrpc"
  rpc_password: "lksjfgiouw345-908lkjdgh"
  rpc_host: 'localhost'
  rpc_port: 1338
darkcoin:
  rpc_username: "darkcoinrpc"
  rpc_password: "lksjfgiouw345-908lkjdgh"
  rpc_host: 'sandbox.noveltylab.com'
  rpc_port: 1338
mastercoin:
  rpc_username: "mastercoin"
  rpc_password: "masterw0rk"
  rpc_host: 'sandbox.noveltylab.com'
  rpc_port: 12333
